### ISSUE TITLE
Configuring Oracles

### ISSUE THREAD

**Issue by logikonline** [AxLabs/neo3-privatenet-docker#20] opened 2022-08-14 17:54 UTC
I see the configurations for each node: [https://github.com/AxLabs/neo3-privatenet-docker/blob/master/config/oracle.config-client1.json](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/config/oracle.config-client1.json)

Can you shed some light on how to activate it?  I see no documentation from NEO on this topic, and I tried setting the Nodes [] property and AutoStart = true. 

But this only results in the client failing to start by exiting 0.

**Comment by logikonline** [comment] 2022-08-14 17:55
`{
  "PluginConfiguration": {
    "Network": 5195086,
    "Nodes": [
      "127.0.0.1:10333" 
    ],
    "MaxTaskTimeout": 432000000,
    "MaxOracleTimeout": 10000,
    "AllowPrivateHost": true,
    "AllowedContentTypes": [ "application/json" ],
    "Https": {
      "Timeout": 5000
    },
    "NeoFS": {
      "EndPoint": "http://127.0.0.1:8080",
      "Timeout": 15000
    },
    "AutoStart": true
  },
  "Dependency": [
    "RpcServer"
  ]
}`

This is my sample - can you suggest the edits to make it work?

**Comment by logikonline** [comment] 2022-08-17 15:14
@gsmachado If you can assist with this, I would gladly become a sponsor for your involvement on this project.

**Comment by gsmachado** [comment] 2022-08-17 15:34
@logikonline absolutely. This issue is assigned to me, for this sprint. 👍 

I will provide you with an answer soon! Didn't forget about it. 😄

**Comment by gsmachado** [comment] 2022-08-18 14:03
@logikonline 
So... to have an oracle working in a privatenet you first need to understand the process on how things work.

The privatenet in this repo intends to provide a raw network, from scratch, without oracles. In order to elect oracles in the network, a holder of a public key (wallet) needs to register as a candidate, designate a role to it, and "start the oracle service".

We, from @AxLabs, are also the maintainers of @neow3j, a Java/Kotlin/Android development toolkit for the Neo ecosystem, where you can develop smart contracts, interact with Neo nodes, etc. In one of our repositories, we have an "integration test" to check if smart contracts calling oracles really work. For this test, we had to first "set up" the oracles, programmatically, and then perform the test by calling a smart contract using the oracle function. You can check the test [here](https://github.com/neow3j/neow3j/blob/main/int-tests/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java#L79-L159). It's a bit difficult to understand, but let me give you the highlights:

1. First, a public key (wallet) needs to register itself as a "candidate" in the network ([lines 85-95](https://github.com/neow3j/neow3j/blob/main/int-tests/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java#L89-L95))
2. Then, the Neo committee members (multisig of all pubkeys from the 21 committee members) should designate the candidate's pubkey with the role of "Oracle". It's like an election, where the Neo network votes on an specific pubkey/node as responsible to make oracle calls. This happens on lines [96-107](https://github.com/neow3j/neow3j/blob/main/int-tests/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java#L96-L107)
3. Then, naturally, the node where the publickey of the now elected Oracle is loaded, should also start the "oracle service" (which is a plugin in the Neo CLI). This happens in line [110](https://github.com/neow3j/neow3j/blob/main/int-tests/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java#L109-L110).
4. That's it. From now on, the oracle service will make API calls requested by smart contracts.

The question is: ok, Guil, how do I do this in practical terms?

Well, you have two options:
1. Either you start a [privatenet using this repo](https://github.com/AxLabs/neo3-privatenet-docker) and orchestrate the aforementioned actions ☝️ programmatically, using an SDK like [neow3j](https://github.com/neow3j/neow3j);
2. or, you can do this manually every single time you bootstrap the [privatenet](https://github.com/AxLabs/neo3-privatenet-docker).

If you go with 1), then I suggest reading how you could develop tests for smart contracts in [neow3j's docs website](https://neow3j.io/#/neo-n3/smart_contract_development/testing). The advantage is that you could have a single development environment to develop+tests your smart contracts, all integrated. Also, you would save tons of time if you want to run test cases over and over again. The disadvantage is that you would have to code way more to set up everything... but in my experience, this time pays off. 😄 

If you go with 2), then you have to execute some commands on the docker container. I'm unable to provide those to you at this time, though. But I will follow up on this.

**Comment by logikonline** [comment] 2022-08-18 16:16
@gsmachado Thank you for the explanation, and while option 1 is enticing, I stumbled across your repo because of the need to run a privatenet locally.  I have the oracle working on the testnet and mainnet, so I feel comfortable with the SC development.

I primarily develop in C#, although have a fair amount of history with Java, so I will try it, but if you could provide the steps for 2, I would greatly appreciate it. 

The script method around docker is really a huge value-add with this repo since I have learned a ton, and the automation is key for me to digest.

**Comment by gsmachado** [comment] 2022-08-18 18:47
As described [here](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/README.md?plain=1#L100), [this repo](https://github.com/AxLabs/neo3-privatenet-docker) has 3 nodes/clients running on the same network. The `neo-consensus` initially has all NEO and GAS in the [loaded multi-sig wallet](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/README.md?plain=1#L110-L112).

As I previously explained, the Neo committee members of the network should designate the candidate's pubkey with the role of "Oracle". It's like if the Neo network "elects" a specific pubkey/node as responsible to make oracle calls.

For this mini-tutorial, we will do the following:

- The `neo-consensus` will designate the pubkey of `neo-client1` as an Oracle in the network.
- The `neo-client1` should start the Oracle service.
- Deploy a smart contract that has a method performing an Oracle call.
- Make a transaction to the method
- Check if the Oracle actually made the API call requested from the smart contract.

Ok, first, you need to:

```
git clone --recurse-submodules https://github.com/AxLabs/neo3-privatenet-docker.git
cd neo3-privatenet-docker
docker-compose up
```

Then, in another terminal window, attach to the `neo-consensus` node by executing the following:

```
docker exec -it neo-consensus screen -r
```

You will attach to the neo-consensus Neo CLI. You will see lots of logs there, since the log is active on the Node. But... don't bother with this. Just type [ENTER] a couple of times and you'll see the `neo>` command line.

Then, copy&paste this command to invoke the "designateAsRole" method on the `RoleManagement` native smart contract (`0x49cf4e5378ffcd4dec034fd98a174c5491e395e2`). The parameters are: 1) Integer `8` representing the role `Oracle` (you can see more roles [here](https://github.com/neow3j/neow3j/blob/main/core/src/main/java/io/neow3j/protocol/core/Role.java#L10-L12)); and PublicKey `02607a38b8010a8f401c25dd01df1b74af1827dd16b821fc07451f2ef7f02da60f`, which is the public key of the wallet loaded to `neo-client1` (see [here](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/README.md?plain=1#L118)).

```
invoke 0x49cf4e5378ffcd4dec034fd98a174c5491e395e2 designateAsRole [{"type":"Integer","value":8},{"type":"Array","value":[{"type":"PublicKey","value":"02607a38b8010a8f401c25dd01df1b74af1827dd16b821fc07451f2ef7f02da60f"}]}] NXXazKH39yNFWWZF5MJ8tEN98VYHwzn7g3 NXXazKH39yNFWWZF5MJ8tEN98VYHwzn7g3
```

The password of the wallet is `neo` (as stated [here](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/README.md?plain=1#L133)).

Once confirmed, you will see a transaction hash as output, like this:

```
0x0838851a1d6e3ca5aa08605c52344a96cfdb8d3abdf6d15d648106a0574b6610
```

Save this tx hash, and type `CTRL+a d` to detach from the `screen` session of the `neo-consensus` node. If you're not familiar with `screen`, I recommend reading [this](https://linuxize.com/post/how-to-use-linux-screen/).

Then, if you want, you can even check whether the transaction `HALT`'ed or `FAIL`'ed by using the `getapplicationlog` JSON-RPC call, using `curl` (this should be done in your host machine, in another terminal):

```
curl http://127.0.0.1:10332 -d '{
	"jsonrpc":"2.0",
	"id":1
	"method":"getapplicationlog",
	"params":[
		"0x0838851a1d6e3ca5aa08605c52344a96cfdb8d3abdf6d15d648106a0574b6610"
	]
}' | jq
```

Then, you can also check that the pubkey `02607a38b8010a8f401c25dd01df1b74af1827dd16b821fc07451f2ef7f02da60f` was really designated as an Oracle:

```
curl http://127.0.0.1:10332 -d '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "invokefunction",
  "params": [
    "0x49cf4e5378ffcd4dec034fd98a174c5491e395e2",
    "getDesignatedByRole",
    [
        {
            "type": "Integer",
            "value": "8"
        },
        {
            "type": "Integer",
            "value": "196"
        }
  	]
  ]
}' | jq
```

The result looks something like this:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "script": "AcQAGBLAHwwTZ2V0RGVzaWduYXRlZEJ5Um9sZQwU4pXjkVRMF4rZTwPsTc3/eFNOz0lBYn1bUg==",
    "state": "HALT",
    "gasconsumed": "2028150",
    "exception": null,
    "notifications": [],
    "stack": [
      {
        "type": "Array",
        "value": [
          {
            "type": "ByteString",
            "value": "AmB6OLgBCo9AHCXdAd8bdK8YJ90WuCH8B0UfLvfwLaYP"
          }
        ]
      }
    ]
  }
}
```

Then, you can copy `AmB6OLgBCo9AHCXdAd8bdK8YJ90WuCH8B0UfLvfwLaYP` (Base64 of a hex string) and go to https://neo.org/converter/index to convert from Base64 to the actual hex string. The result should be `02607a38b8010a8f401c25dd01df1b74af1827dd16b821fc07451f2ef7f02da60f` -- which is actually the pubkey. This means it worked.

Now, go to your host machine and attach to the `neo-client1` docker container:

```
docker exec -it neo-client1 screen -r
```

Then, you can type the following to the `neo>` command line:

```
start oracle
```

to start the Oracle service (which is a plugin in the Neo Node).

Also, you can type

```
oracle status
```

to check if it's really running.

Type `CTRL+a d` to detach from the `screen` session of the `neo-consensus` node. 👍 

Ok, now we need a smart contract capable of making an Oracle call. 🥇 

I will use the https://github.com/neow3j/neow3j-examples-java repo, which, in my opinion, provides three great things:

- `CallOracleContract` smart contract ([see here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/CallOracleContract.java)): basically, it has a `request` method (to be invoked by you) and a `callback` (to be invoked by the Oracle service). The `callback` puts the result (i.e., response) of the `url` API request to the contract storage. Simple.
- `OracleMakeRequest` example ([see here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractinvoke/OracleMakeRequest.java)): it's a Java class that calls the deployed `CallOracleContract` contract (`request` method), using the https://jsonplaceholder.typicode.com/todos/1 URL as a param.
- `OracleCheckResponse` example ([see here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractinvoke/OracleCheckResponse.java)): it's a Java class that simply reads the storage of the deployed `CallOracleContract` contract, just to check if the `callback` function ([see here](https://github.com/neow3j/neow3j-examples-java/blob/master/src/main/java/io/neow3j/examples/contractdevelopment/contracts/CallOracleContract.java#L21-L23)) really added the response to the storage. If it's added, then it means the Oracle could successfully be called. 🚀 

I will not cover the whole part of setting up the https://github.com/neow3j/neow3j-examples-java repo, deploying the `CallOracleContract` smart contract, and running both `OracleMakeRequest` and `OracleCheckResponse` classes. However, I tell you that it works, 100%, since I've followed the steps described above. 😄 😅 

That's it for today. I might convert this to a Medium post.

Let me know if it worked! 🍀

**Comment by gsmachado** [comment] 2022-08-18 18:55
I might try to automate [this process](https://github.com/AxLabs/neo3-privatenet-docker/issues/20#issuecomment-1219820720) part of https://github.com/AxLabs/neo3-privatenet-docker/issues/12. But maybe it will take some days/time.

**Comment by logikonline** [comment] 2022-08-18 19:45
@gsmachado thank you again.  And you should make it a Medium post cause there are no docs on this.

**Closed as completed** 2022-08-18 19:45 UTC
Labels: good first issue

**Comment by gsmachado** [comment] 2022-08-18 19:51
@logikonline just curious: what are you building?

**Comment by logikonline** [comment] 2022-08-18 20:11
@gsmachado I am building an end-to-end solution for the public with my take on no passwords (I don’t care for the FIDO approach of Apple/M$/Google) that is a more robust method of commerce that removes some of the pitfalls around using blockchain.  NEO is by far the best-in-class platform after evaluating half a dozen solutions.

I just wrapped up a 7 year AI project that is now automated, so I want to tackle this problem.  I have been disappointed in nearly every blockchain solution since dabbling in the space around 2016 with Consensus/Ethereum.

**Comment by gsmachado** [comment] 2022-08-19 12:51
> @gsmachado I am building an end-to-end solution for the public with my take on no passwords (I don’t care for the FIDO approach of Apple/M$/Google) that is a more robust method of commerce that removes some of the pitfalls around using blockchain. NEO is by far the best-in-class platform after evaluating half a dozen solutions.
> 
> I just wrapped up a 7 year AI project that is now automated, so I want to tackle this problem. I have been disappointed in nearly every blockchain solution since dabbling in the space around 2016 with Consensus/Ethereum.

That's awesome to hear, @logikonline.

So, I would be willing to chat with you and/or your team. It seems interesting. 😄 

Can you please consider joining @AxLabs Discord server? Info below.

Website: https://axlabs.com
Discord: https://discord.gg/RBukhnEeke
